name: Upload Module Release

on:
  push:
    tags:
      - "v*"

jobs:
  upload-module:
    name: Upload module to Viam
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          # Remove 'v' prefix from tag name
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Viam CLI
        run: |
          curl -o viam https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-stable-linux-amd64
          chmod +x viam
          sudo mv viam /usr/local/bin/

      - name: Verify Viam CLI installation
        run: viam version

      - name: Authenticate with Viam
        env:
          VIAM_API_KEY_ID: ${{ secrets.VIAM_API_KEY_ID }}
          VIAM_API_KEY: ${{ secrets.VIAM_API_KEY }}
        run: |
          viam auth api-key --key-id "$VIAM_API_KEY_ID" --key "$VIAM_API_KEY"

      - name: Read platforms from meta.json
        id: platforms
        run: |
          PLATFORMS=$(jq -r '.build.arch | join(" ")' meta.json)
          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT
          echo "Platforms to upload: $PLATFORMS"

      - name: Upload module for each platform
        env:
          VERSION: ${{ steps.extract_version.outputs.version }}
        run: |
          PLATFORMS="${{ steps.platforms.outputs.platforms }}"

          echo "Uploading version $VERSION to platforms: $PLATFORMS"

          for PLATFORM in $PLATFORMS; do
            echo "Uploading to platform: $PLATFORM"
            viam module upload --version "$VERSION" --platform "$PLATFORM" . || {
              echo "Error: Failed to upload to platform $PLATFORM"
              exit 1
            }
            echo "✓ Successfully uploaded to $PLATFORM"
          done

          echo ""
          echo "=================================================="
          echo "✓ All platforms uploaded successfully!"
          echo "=================================================="
